# Generated by Django 3.2.8 on 2021-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ptarkalis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarkaliname', models.CharField(max_length=30)),
                ('tarkaliprice', models.FloatField()),
                ('tarkalicode', models.IntegerField()),
            ],
        ),
    ]
